### ISSUE TITLE
Fix styling

### ISSUE THREAD

**Issue by dewanshrawat15** [dscbvppune/Startup-Vadodara#6]
On hovering over the "Join the journey" button on the hero section, the button shows an underline. It would be preferable if the underline did not show.

**Comment by shikhargupta-in** [comment]
Hi, @dewanshrawat15 can I work on this issue?

**Comment by SuyashGupte** [comment]
I am working on this issue, assign this task to me.

**Comment by arhaanb** [comment]
Hey can you assign this to me? I can fix it

**Comment by yashikacac** [comment]
@dewanshrawat15 I would like to work on this issue.

**Comment by dewanshrawat15** [comment]
@yashikacac have been assigned to the issue. Good luck 👍

**Comment by dewanshrawat15** [comment]
@arhaanb @SuyashGupte @shikhargupta-in thank you for your interest in this repository. It's great to see your activeness. While this did not pan out, please do check out other issues where you could contribute to.

Thanks!

**Comment by dewanshrawat15** [comment]
Resolved!
