### ISSUE TITLE
Optimise page load time

### ISSUE THREAD

**Issue by dewanshrawat15** [dscbvppune/Startup-Vadodara#8]
The size of the website right now is rough about 3MB. If that could be reduced dynamically, it would help a lot to load the page on a poor internet connection too. Making it a PWA, or caching it through a service worker, making it available offline could be potential fixes.

**Comment by Nishchayverma** [comment]
First of all images can be converted to .webp format to significantly reduce image size and can be lazyloaded using a vanilla JS lazyload library OR use  <img loading=lazy> , which is supported by most popular Chromium-powered browsers (Chrome, Edge, Opera) and Firefox. 
Then the resources that are appearing in FCP can be preloaded using
 <link rel="preload" href="{image}">
 and resources in next navigation pages can be prefetched using 
<link rel="prefetch" href="{image}"> 
. This helps in caching files.

**Comment by dewanshrawat15** [comment]
Sounds like a good plan, go ahead!
